//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSCADA6.HMI.NSHMIForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetSCADA6.HMI.NSHMIForm.Rs", typeof(Rs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下对齐.
        /// </summary>
        internal static string sAlignBottom {
            get {
                return ResourceManager.GetString("sAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直居中.
        /// </summary>
        internal static string sAlignCenter {
            get {
                return ResourceManager.GetString("sAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左对齐.
        /// </summary>
        internal static string sAlignLeft {
            get {
                return ResourceManager.GetString("sAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平居中.
        /// </summary>
        internal static string sAlignMiddle {
            get {
                return ResourceManager.GetString("sAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右对齐.
        /// </summary>
        internal static string sAlignRight {
            get {
                return ResourceManager.GetString("sAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上对齐.
        /// </summary>
        internal static string sAlignTop {
            get {
                return ResourceManager.GetString("sAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置后一层.
        /// </summary>
        internal static string sBack {
            get {
                return ResourceManager.GetString("sBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小水平距离.
        /// </summary>
        internal static string sDecrHSpace {
            get {
                return ResourceManager.GetString("sDecrHSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩小垂直距离.
        /// </summary>
        internal static string sDecrVSpace {
            get {
                return ResourceManager.GetString("sDecrVSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平翻转.
        /// </summary>
        internal static string sFlipX {
            get {
                return ResourceManager.GetString("sFlipX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直翻转.
        /// </summary>
        internal static string sFlipY {
            get {
                return ResourceManager.GetString("sFlipY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 置前一层.
        /// </summary>
        internal static string sFront {
            get {
                return ResourceManager.GetString("sFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网格模式.
        /// </summary>
        internal static string sGrid {
            get {
                return ResourceManager.GetString("sGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成组.
        /// </summary>
        internal static string sGroup {
            get {
                return ResourceManager.GetString("sGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平等距.
        /// </summary>
        internal static string sHSpace {
            get {
                return ResourceManager.GetString("sHSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩大水平距离.
        /// </summary>
        internal static string sIncrHSpace {
            get {
                return ResourceManager.GetString("sIncrHSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩大垂直距离.
        /// </summary>
        internal static string sIncrVSpace {
            get {
                return ResourceManager.GetString("sIncrVSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最后.
        /// </summary>
        internal static string sLast {
            get {
                return ResourceManager.GetString("sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图层配置.
        /// </summary>
        internal static string sLayer {
            get {
                return ResourceManager.GetString("sLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正交模式.
        /// </summary>
        internal static string sOrtho {
            get {
                return ResourceManager.GetString("sOrtho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等高.
        /// </summary>
        internal static string sSameHeight {
            get {
                return ResourceManager.GetString("sSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等尺寸.
        /// </summary>
        internal static string sSameSize {
            get {
                return ResourceManager.GetString("sSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等宽.
        /// </summary>
        internal static string sSameWidth {
            get {
                return ResourceManager.GetString("sSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗体缩放.
        /// </summary>
        internal static string sScale {
            get {
                return ResourceManager.GetString("sScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最前.
        /// </summary>
        internal static string sTop {
            get {
                return ResourceManager.GetString("sTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解组.
        /// </summary>
        internal static string sUnGroup {
            get {
                return ResourceManager.GetString("sUnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直等距.
        /// </summary>
        internal static string sVSpace {
            get {
                return ResourceManager.GetString("sVSpace", resourceCulture);
            }
        }
    }
}
