//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSCADA6.HMI.NSHMIFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetSCADA6.HMI.NSHMIFramework.Rs", typeof(Rs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon iAddDir {
            get {
                object obj = ResourceManager.GetObject("iAddDir", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iAddFile {
            get {
                object obj = ResourceManager.GetObject("iAddFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iCopy {
            get {
                object obj = ResourceManager.GetObject("iCopy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iDelete {
            get {
                object obj = ResourceManager.GetObject("iDelete", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iDir {
            get {
                object obj = ResourceManager.GetObject("iDir", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iFile {
            get {
                object obj = ResourceManager.GetObject("iFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iPaste {
            get {
                object obj = ResourceManager.GetObject("iPaste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon iRoot {
            get {
                object obj = ResourceManager.GetObject("iRoot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加文件夹.
        /// </summary>
        internal static string sAddDirectory {
            get {
                return ResourceManager.GetString("sAddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加窗口.
        /// </summary>
        internal static string sAddFile {
            get {
                return ResourceManager.GetString("sAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string sCopy {
            get {
                return ResourceManager.GetString("sCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复件.
        /// </summary>
        internal static string sCopyName {
            get {
                return ResourceManager.GetString("sCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string sDelete {
            get {
                return ResourceManager.GetString("sDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .gdi.
        /// </summary>
        internal static string sExtension {
            get {
                return ResourceManager.GetString("sExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建文件夹.
        /// </summary>
        internal static string sNewDirName {
            get {
                return ResourceManager.GetString("sNewDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建窗体.
        /// </summary>
        internal static string sNewFileName {
            get {
                return ResourceManager.GetString("sNewFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMI.
        /// </summary>
        internal static string sNodeSign {
            get {
                return ResourceManager.GetString("sNodeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称不能为空.
        /// </summary>
        internal static string sNullHint {
            get {
                return ResourceManager.GetString("sNullHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string sPaste {
            get {
                return ResourceManager.GetString("sPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        internal static string sRename {
            get {
                return ResourceManager.GetString("sRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称已存在.
        /// </summary>
        internal static string sRepeatHint {
            get {
                return ResourceManager.GetString("sRepeatHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图形窗体.
        /// </summary>
        internal static string sRootName {
            get {
                return ResourceManager.GetString("sRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父目录不能拷贝到子目录中.
        /// </summary>
        internal static string sSubToParentHint {
            get {
                return ResourceManager.GetString("sSubToParentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矢量控件.
        /// </summary>
        internal static string sVectorTabName {
            get {
                return ResourceManager.GetString("sVectorTabName", resourceCulture);
            }
        }
    }
}
